List cards = [
  { "id": "1c",
    "name": "Mohammed Saleh",
    "Tagline.": "Photographer For Any Event",
    "logo": "https://www.meritnation.com/blog/wp-content/upLoads/3_vintage-camera-png-icon-camera-png-10.png",
    "location": "Qassim",
    "link": "https://www.pexels.com/@eberhardgross",
    "service":"photo",
    "qr_code":"assets/images/qrcode_2868271_.png",
    "Contact details":"022232432"
  },
  { "id": "2c",
    "name": "Almarai Company",
    "Tagline.": "Almarai Company is a Saudi multinational dairy company which is listed on the Tadawul stock exchange.",
    "logo": "https://download.logo.wine/logo/Almarai/Almarai-Logo.wine.png",
    "location": "Riyadh",
    "link": "https://www.pexels.com/@eberhardgross",
    "service":"Selling Products",
    "qr_code":"assets/images/qrcode_2868271_.png",
    "Contact details":"022232432"
  },
  { "id": "3c",
    "name": "Faisal Aldayel",
    "Tagline.": "Almarai Company is a Saudi multinational dairy company which is listed on the Tadawul stock exchange.",
    "logo": "https://media.zid.store/cdn-cgi/image/h=220,q=100,f=auto/https://media.zid.store/10592c2d-ba57-4bf5-82b1-eb2082c55b8a/380befb0-f994-4355-bc5c-7933d7090584-200x.jpg",
    "location": "Riyadh",
    "link": "https://www.pexels.com/@eberhardgross",
    "service":"Selling Products",
    "qr_code":"assets/images/qrcode_2868271_.png",
    "Contact details":"022232432"
  },
  { "id": "4c",
    "name": "SABIC",
    "Tagline.": "Almarai Company is a Saudi multinational dairy company which is listed on the Tadawul stock exchange.",
    "logo": "https://download.logo.wine/logo/Almarai/Almarai-Logo.wine.png",
    "location": "Riyadh",
    "link": "https://www.pexels.com/@eberhardgross",
    "service":"Selling Products",
    "qr_code":"assets/images/qrcode_2868271_.png",
    "Contact details":"022232432"
  },
  { "id": "5c",
    "name": "STC",
    "Tagline.": "Almarai Company is a Saudi multinational dairy company which is listed on the Tadawul stock exchange.",
    "logo": "https://download.logo.wine/logo/Almarai/Almarai-Logo.wine.png",
    "location": "Riyadh",
    "link": "https://www.pexels.com/@eberhardgross",
    "service":"Selling Products",
    "qr_code":"assets/images/qrcode_2868271_.png",
    "Contact details":"022232432"
  },
  { "id": "6c",
    "name": "Foodics",
    "Tagline.": "Almarai Company is a Saudi multinational dairy company which is listed on the Tadawul stock exchange.",
    "logo": "https://download.logo.wine/logo/Almarai/Almarai-Logo.wine.png",
    "location": "Riyadh",
    "link": "https://www.pexels.com/@eberhardgross",
    "service":"Selling Products",
    "qr_code":"assets/images/qrcode_2868271_.png",
    "Contact details":"022232432"
  },
  { "id": "7c",
    "name": "Nana Direct",
    "Tagline.": "Almarai Company is a Saudi multinational dairy company which is listed on the Tadawul stock exchange.",
    "logo": "https://download.logo.wine/logo/Almarai/Almarai-Logo.wine.png",
    "location": "Riyadh",
    "link": "https://www.pexels.com/@eberhardgross",
    "service":"Selling Products",
    "qr_code":"assets/images/qrcode_2868271_.png",
    "Contact details":"022232432"
  },
  { "id": "8c",
    "name": "Noon",
    "Tagline.": "Almarai Company is a Saudi multinational dairy company which is listed on the Tadawul stock exchange.",
    "logo": "https://download.logo.wine/logo/Almarai/Almarai-Logo.wine.png",
    "location": "Riyadh",
    "link": "https://www.pexels.com/@eberhardgross",
    "service":"Selling Products",
    "qr_code":"assets/images/qrcode_2868271_.png",
    "Contact details":"022232432"
  },
];
